import MyImgUrl from "../assets/Habitation-information_banner.png";
import MyImgUrlMobile from "../assets/Habitation-information_banner--mobile.png";

export const data = [
  {
    id: 123,
    habitationName: "Cozy loft on the Canal Saint-Martin",
    habitationPictures: [
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
    ],
    location: "Paris, Île-de-France",
    owner: { firstName: "Alexandre", lastName: "Dumas", imgSrc: "" },
    tags: ["Cozy", "Canal", "Paris 10"],
    reviewScore: 3,
    description:
      "Vous serez à 50m du canal Saint-martin où vous pourrez pique-niquer l'été et à côté de nombreux bars et restaurants. Au cœur de Paris avec 5 lignes de métro et de nombreux bus. Logement parfait pour les voyageurs en solo et les voyageurs d'affaires. Vous êtes à1 station de la gare de l'est (7 minutes à pied). ",
    equipments: [
      "Climatisation",
      "Wi-Fi",
      "Cuisine",
      "Espace de travail",
      "Fer à repasser",
      "Sèche-cheveux",
      "Cintres",
    ],
  },
  {
    id: 123,
    habitationName: "Cozy loft on the Canal Saint-Martin",
    habitationPictures: [{ desktop: MyImgUrl, mobile: MyImgUrlMobile }],
    location: "Paris, Île-de-France",
    owner: { firstName: "Alexandre", lastName: "Dumas", imgSrc: "" },
    tags: ["Cozy", "Canal", "Paris 10"],
    reviewScore: 3,
    description:
      "Vous serez à 50m du canal Saint-martin où vous pourrez pique-niquer l'été et à côté de nombreux bars et restaurants. Au cœur de Paris avec 5 lignes de métro et de nombreux bus. Logement parfait pour les voyageurs en solo et les voyageurs d'affaires. Vous êtes à1 station de la gare de l'est (7 minutes à pied). ",
    equipments: [
      "Climatisation",
      "Wi-Fi",
      "Cuisine",
      "Espace de travail",
      "Fer à repasser",
      "Sèche-cheveux",
      "Cintres",
    ],
  },
  {
    id: 123,
    habitationName: "Cozy loft on the Canal Saint-Martin",
    habitationPictures: [
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
    ],
    location: "Paris, Île-de-France",
    owner: { firstName: "Alexandre", lastName: "Dumas", imgSrc: "" },
    tags: ["Cozy", "Canal", "Paris 10"],
    reviewScore: 3,
    description:
      "Vous serez à 50m du canal Saint-martin où vous pourrez pique-niquer l'été et à côté de nombreux bars et restaurants. Au cœur de Paris avec 5 lignes de métro et de nombreux bus. Logement parfait pour les voyageurs en solo et les voyageurs d'affaires. Vous êtes à1 station de la gare de l'est (7 minutes à pied). ",
    equipments: [
      "Climatisation",
      "Wi-Fi",
      "Cuisine",
      "Espace de travail",
      "Fer à repasser",
      "Sèche-cheveux",
      "Cintres",
    ],
  },
  {
    id: 123,
    habitationName: "Cozy loft on the Canal Saint-Martin",
    habitationPictures: [
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
    ],
    location: "Paris, Île-de-France",
    owner: { firstName: "Alexandre", lastName: "Dumas", imgSrc: "" },
    tags: ["Cozy", "Canal", "Paris 10"],
    reviewScore: 3,
    description:
      "Vous serez à 50m du canal Saint-martin où vous pourrez pique-niquer l'été et à côté de nombreux bars et restaurants. Au cœur de Paris avec 5 lignes de métro et de nombreux bus. Logement parfait pour les voyageurs en solo et les voyageurs d'affaires. Vous êtes à1 station de la gare de l'est (7 minutes à pied). ",
    equipments: [
      "Climatisation",
      "Wi-Fi",
      "Cuisine",
      "Espace de travail",
      "Fer à repasser",
      "Sèche-cheveux",
      "Cintres",
    ],
  },
  {
    id: 123,
    habitationName: "Cozy loft on the Canal Saint-Martin",
    habitationPictures: [
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
    ],
    location: "Paris, Île-de-France",
    owner: { firstName: "Alexandre", lastName: "Dumas", imgSrc: "" },
    tags: ["Cozy", "Canal", "Paris 10"],
    reviewScore: 3,
    description:
      "Vous serez à 50m du canal Saint-martin où vous pourrez pique-niquer l'été et à côté de nombreux bars et restaurants. Au cœur de Paris avec 5 lignes de métro et de nombreux bus. Logement parfait pour les voyageurs en solo et les voyageurs d'affaires. Vous êtes à1 station de la gare de l'est (7 minutes à pied). ",
    equipments: [
      "Climatisation",
      "Wi-Fi",
      "Cuisine",
      "Espace de travail",
      "Fer à repasser",
      "Sèche-cheveux",
      "Cintres",
    ],
  },
  {
    id: 123,
    habitationName: "Cozy loft on the Canal Saint-Martin",
    habitationPictures: [
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
    ],
    location: "Paris, Île-de-France",
    owner: { firstName: "Alexandre", lastName: "Dumas", imgSrc: "" },
    tags: ["Cozy", "Canal", "Paris 10"],
    reviewScore: 3,
    description:
      "Vous serez à 50m du canal Saint-martin où vous pourrez pique-niquer l'été et à côté de nombreux bars et restaurants. Au cœur de Paris avec 5 lignes de métro et de nombreux bus. Logement parfait pour les voyageurs en solo et les voyageurs d'affaires. Vous êtes à1 station de la gare de l'est (7 minutes à pied). ",
    equipments: [
      "Climatisation",
      "Wi-Fi",
      "Cuisine",
      "Espace de travail",
      "Fer à repasser",
      "Sèche-cheveux",
      "Cintres",
    ],
  },
  {
    id: 123,
    habitationName: "Cozy loft on the Canal Saint-Martin",
    habitationPictures: [
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
    ],
    location: "Paris, Île-de-France",
    owner: { firstName: "Alexandre", lastName: "Dumas", imgSrc: "" },
    tags: ["Cozy", "Canal", "Paris 10"],
    reviewScore: 3,
    description:
      "Vous serez à 50m du canal Saint-martin où vous pourrez pique-niquer l'été et à côté de nombreux bars et restaurants. Au cœur de Paris avec 5 lignes de métro et de nombreux bus. Logement parfait pour les voyageurs en solo et les voyageurs d'affaires. Vous êtes à1 station de la gare de l'est (7 minutes à pied). ",
    equipments: [
      "Climatisation",
      "Wi-Fi",
      "Cuisine",
      "Espace de travail",
      "Fer à repasser",
      "Sèche-cheveux",
      "Cintres",
    ],
  },
  {
    id: 123,
    habitationName: "Cozy loft on the Canal Saint-Martin",
    habitationPictures: [
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
    ],
    location: "Paris, Île-de-France",
    owner: { firstName: "Alexandre", lastName: "Dumas", imgSrc: "" },
    tags: ["Cozy", "Canal", "Paris 10"],
    reviewScore: 3,
    description:
      "Vous serez à 50m du canal Saint-martin où vous pourrez pique-niquer l'été et à côté de nombreux bars et restaurants. Au cœur de Paris avec 5 lignes de métro et de nombreux bus. Logement parfait pour les voyageurs en solo et les voyageurs d'affaires. Vous êtes à1 station de la gare de l'est (7 minutes à pied). ",
    equipments: [
      "Climatisation",
      "Wi-Fi",
      "Cuisine",
      "Espace de travail",
      "Fer à repasser",
      "Sèche-cheveux",
      "Cintres",
    ],
  },
  {
    id: 123,
    habitationName: "Cozy loft on the Canal Saint-Martin",
    habitationPictures: [
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
      { desktop: MyImgUrl, mobile: MyImgUrlMobile },
    ],
    location: "Paris, Île-de-France",
    owner: { firstName: "Alexandre", lastName: "Dumas", imgSrc: "" },
    tags: ["Cozy", "Canal", "Paris 10"],
    reviewScore: 3,
    description:
      "Vous serez à 50m du canal Saint-martin où vous pourrez pique-niquer l'été et à côté de nombreux bars et restaurants. Au cœur de Paris avec 5 lignes de métro et de nombreux bus. Logement parfait pour les voyageurs en solo et les voyageurs d'affaires. Vous êtes à1 station de la gare de l'est (7 minutes à pied). ",
    equipments: [
      "Climatisation",
      "Wi-Fi",
      "Cuisine",
      "Espace de travail",
      "Fer à repasser",
      "Sèche-cheveux",
      "Cintres",
    ],
  },
];
